repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-ast
  - id: check-yaml
  - id: debug-statements
- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
    - id: isort
      args: ["--profile", "black", "--filter-files", "--line-length 120"]
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
  - id: flake8
    args:
      - "--max-line-length=120"
      - "--ignore=E203,W503,E731"
      - "--per-file-ignores=__init__.py:E402,F401,F403,F405"
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.971
  hooks:
  - id: mypy
    exclude: 'notebooks|scripts'
    additional_dependencies: ['types-PyYAML']
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black
