name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  SE_EXECUTABLE: source-extractor

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: install packages
        run: |
          sudo apt-get install sextractor
          pip install -e ".[dev]"
      - name: unit tests
        run: pytest -v .
      - name: type checking
        run: mypy src/sew --ignore-missing-imports
      - name: linting
        run: flake8 src/sew
